In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Introduction

### Step 1: Import libraries
- requests
- pandas as pd
- datetime
- time

In [2]:
# Step 1: Import libraries
import requests
import pandas as pd
import datetime
import time

# Testing collection
Before we collect data en masse, we should collect the data bit by bit first and measure the time taken to assess the right strategy.

We'll start by making simple class first, then building up for more while keeping an expectation of how much time these tasks will take.

### Step 2: Create a range of dates and time
We'll be retrieving a day's worth of data first, with an interval of 1 minute. 

We do that because the API documentation recommends so. Use pandas' date range to get a range of time between "2019/01/01" and "2019/01/02", with a frequency of 1 minute.

![DataRangeExample](https://uplevelsg.s3-ap-southeast-1.amazonaws.com/ProjectComputerVisionTraffic/DataRangeOneDay.png)

Your list will be 1,441 items long.

In [3]:
# Step 2: Get a range of dates and time
date_range=pd.date_range(start='1/1/2019', end='1/2/2019',freq="1T")
date_range

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 00:01:00',
               '2019-01-01 00:02:00', '2019-01-01 00:03:00',
               '2019-01-01 00:04:00', '2019-01-01 00:05:00',
               '2019-01-01 00:06:00', '2019-01-01 00:07:00',
               '2019-01-01 00:08:00', '2019-01-01 00:09:00',
               ...
               '2019-01-01 23:51:00', '2019-01-01 23:52:00',
               '2019-01-01 23:53:00', '2019-01-01 23:54:00',
               '2019-01-01 23:55:00', '2019-01-01 23:56:00',
               '2019-01-01 23:57:00', '2019-01-01 23:58:00',
               '2019-01-01 23:59:00', '2019-01-02 00:00:00'],
              dtype='datetime64[ns]', length=1441, freq='T')

In [4]:
# Optional: Check length of list
len(date_range)

1441

### Step 3: Format the datetime into a string

In [5]:
# Step 3: Format the first datetime in list to string
date_range_string=[str(i)[:10]+"T"+str(i)[11:] for i in date_range]
date_range_string

['2019-01-01T00:00:00',
 '2019-01-01T00:01:00',
 '2019-01-01T00:02:00',
 '2019-01-01T00:03:00',
 '2019-01-01T00:04:00',
 '2019-01-01T00:05:00',
 '2019-01-01T00:06:00',
 '2019-01-01T00:07:00',
 '2019-01-01T00:08:00',
 '2019-01-01T00:09:00',
 '2019-01-01T00:10:00',
 '2019-01-01T00:11:00',
 '2019-01-01T00:12:00',
 '2019-01-01T00:13:00',
 '2019-01-01T00:14:00',
 '2019-01-01T00:15:00',
 '2019-01-01T00:16:00',
 '2019-01-01T00:17:00',
 '2019-01-01T00:18:00',
 '2019-01-01T00:19:00',
 '2019-01-01T00:20:00',
 '2019-01-01T00:21:00',
 '2019-01-01T00:22:00',
 '2019-01-01T00:23:00',
 '2019-01-01T00:24:00',
 '2019-01-01T00:25:00',
 '2019-01-01T00:26:00',
 '2019-01-01T00:27:00',
 '2019-01-01T00:28:00',
 '2019-01-01T00:29:00',
 '2019-01-01T00:30:00',
 '2019-01-01T00:31:00',
 '2019-01-01T00:32:00',
 '2019-01-01T00:33:00',
 '2019-01-01T00:34:00',
 '2019-01-01T00:35:00',
 '2019-01-01T00:36:00',
 '2019-01-01T00:37:00',
 '2019-01-01T00:38:00',
 '2019-01-01T00:39:00',
 '2019-01-01T00:40:00',
 '2019-01-01T00:41:00',
 '2019-01-01T00:42:00',
 '2019-01-01T00:43:00',
 '2019-01-01T00:44:00',
 '2019-01-01T00:45:00',
 '2019-01-01T00:46:00',
 '2019-01-01T00:47:00',
 '2019-01-01T00:48:00',
 '2019-01-01T00:49:00',
 '2019-01-01T00:50:00',
 '2019-01-01T00:51:00',
 '2019-01-01T00:52:00',
 '2019-01-01T00:53:00',
 '2019-01-01T00:54:00',
 '2019-01-01T00:55:00',
 '2019-01-01T00:56:00',
 '2019-01-01T00:57:00',
 '2019-01-01T00:58:00',
 '2019-01-01T00:59:00',
 '2019-01-01T01:00:00',
 '2019-01-01T01:01:00',
 '2019-01-01T01:02:00',
 '2019-01-01T01:03:00',
 '2019-01-01T01:04:00',
 '2019-01-01T01:05:00',
 '2019-01-01T01:06:00',
 '2019-01-01T01:07:00',
 '2019-01-01T01:08:00',
 '2019-01-01T01:09:00',
 '2019-01-01T01:10:00',
 '2019-01-01T01:11:00',
 '2019-01-01T01:12:00',
 '2019-01-01T01:13:00',
 '2019-01-01T01:14:00',
 '2019-01-01T01:15:00',
 '2019-01-01T01:16:00',
 '2019-01-01T01:17:00',
 '2019-01-01T01:18:00',
 '2019-01-01T01:19:00',
 '2019-01-01T01:20:00',
 '2019-01-01T01:21:00',
 '2019-01-01T01:22:00',
 '2019-01-01T01:23:00',
 '2019-01-01T01:24:00',
 '2019-01-01T01:25:00',
 '2019-01-01T01:26:00',
 '2019-01-01T01:27:00',
 '2019-01-01T01:28:00',
 '2019-01-01T01:29:00',
 '2019-01-01T01:30:00',
 '2019-01-01T01:31:00',
 '2019-01-01T01:32:00',
 '2019-01-01T01:33:00',
 '2019-01-01T01:34:00',
 '2019-01-01T01:35:00',
 '2019-01-01T01:36:00',
 '2019-01-01T01:37:00',
 '2019-01-01T01:38:00',
 '2019-01-01T01:39:00',
 '2019-01-01T01:40:00',
 '2019-01-01T01:41:00',
 '2019-01-01T01:42:00',
 '2019-01-01T01:43:00',
 '2019-01-01T01:44:00',
 '2019-01-01T01:45:00',
 '2019-01-01T01:46:00',
 '2019-01-01T01:47:00',
 '2019-01-01T01:48:00',
 '2019-01-01T01:49:00',
 '2019-01-01T01:50:00',
 '2019-01-01T01:51:00',
 '2019-01-01T01:52:00',
 '2019-01-01T01:53:00',
 '2019-01-01T01:54:00',
 '2019-01-01T01:55:00',
 '2019-01-01T01:56:00',
 '2019-01-01T01:57:00',
 '2019-01-01T01:58:00',
 '2019-01-01T01:59:00',
 '2019-01-01T02:00:00',
 '2019-01-01T02:01:00',
 '2019-01-01T02:02:00',
 '2019-01-01T02:03:00',
 '2019-01-01T02:04:00',
 '2019-01-01T02:05:00',
 '2019-01-01T02:06:00',
 '2019-01-01T02:07:00',
 '2019-01-01T02:08:00',
 '2019-01-01T02:09:00',
 '2019-01-01T02:10:00',
 '2019-01-01T02:11:00',
 '2019-01-01T02:12:00',
 '2019-01-01T02:13:00',
 '2019-01-01T02:14:00',
 '2019-01-01T02:15:00',
 '2019-01-01T02:16:00',
 '2019-01-01T02:17:00',
 '2019-01-01T02:18:00',
 '2019-01-01T02:19:00',
 '2019-01-01T02:20:00',
 '2019-01-01T02:21:00',
 '2019-01-01T02:22:00',
 '2019-01-01T02:23:00',
 '2019-01-01T02:24:00',
 '2019-01-01T02:25:00',
 '2019-01-01T02:26:00',
 '2019-01-01T02:27:00',
 '2019-01-01T02:28:00',
 '2019-01-01T02:29:00',
 '2019-01-01T02:30:00',
 '2019-01-01T02:31:00',
 '2019-01-01T02:32:00',
 '2019-01-01T02:33:00',
 '2019-01-01T02:34:00',
 '2019-01-01T02:35:00',
 '2019-01-01T02:36:00',
 '2019-01-01T02:37:00',
 '2019-01-01T02:38:00',
 '2019-01-01T02:39:00',
 '2019-01-01T02:40:00',
 '2019-01-01T02:41:00',
 '2019-01-01T02:42:00',
 '2019-01-01T02:43:00',
 '2019-01-01T02:44:00',
 '2019-01-01T02:45:00',
 '2019-01-01T02:46:00',
 '2019-01-01T02:47:00',
 '2019-01-01T02:48:00',
 '2019-01-01T02:49:00',
 '2019-01-01T02:50:00',
 '2019-01-01T02:51:00',
 '2019-01-01T02:52:00',
 '2019-01-01T02:53:00',
 '2019-01-01T02:54:00',
 '2019-01-01T02:55:00',
 '2019-01-01T02:56:00',
 '2019-01-01T02:57:00',
 '2019-01-01T02:58:00',
 '2019-01-01T02:59:00',
 '2019-01-01T03:00:00',
 '2019-01-01T03:01:00',
 '2019-01-01T03:02:00',
 '2019-01-01T03:03:00',
 '2019-01-01T03:04:00',
 '2019-01-01T03:05:00',
 '2019-01-01T03:06:00',
 '2019-01-01T03:07:00',
 '2019-01-01T03:08:00',
 '2019-01-01T03:09:00',
 '2019-01-01T03:10:00',
 '2019-01-01T03:11:00',
 '2019-01-01T03:12:00',
 '2019-01-01T03:13:00',
 '2019-01-01T03:14:00',
 '2019-01-01T03:15:00',
 '2019-01-01T03:16:00',
 '2019-01-01T03:17:00',
 '2019-01-01T03:18:00',
 '2019-01-01T03:19:00',
 '2019-01-01T03:20:00',
 '2019-01-01T03:21:00',
 '2019-01-01T03:22:00',
 '2019-01-01T03:23:00',
 '2019-01-01T03:24:00',
 '2019-01-01T03:25:00',
 '2019-01-01T03:26:00',
 '2019-01-01T03:27:00',
 '2019-01-01T03:28:00',
 '2019-01-01T03:29:00',
 '2019-01-01T03:30:00',
 '2019-01-01T03:31:00',
 '2019-01-01T03:32:00',
 '2019-01-01T03:33:00',
 '2019-01-01T03:34:00',
 '2019-01-01T03:35:00',
 '2019-01-01T03:36:00',
 '2019-01-01T03:37:00',
 '2019-01-01T03:38:00',
 '2019-01-01T03:39:00',
 '2019-01-01T03:40:00',
 '2019-01-01T03:41:00',
 '2019-01-01T03:42:00',
 '2019-01-01T03:43:00',
 '2019-01-01T03:44:00',
 '2019-01-01T03:45:00',
 '2019-01-01T03:46:00',
 '2019-01-01T03:47:00',
 '2019-01-01T03:48:00',
 '2019-01-01T03:49:00',
 '2019-01-01T03:50:00',
 '2019-01-01T03:51:00',
 '2019-01-01T03:52:00',
 '2019-01-01T03:53:00',
 '2019-01-01T03:54:00',
 '2019-01-01T03:55:00',
 '2019-01-01T03:56:00',
 '2019-01-01T03:57:00',
 '2019-01-01T03:58:00',
 '2019-01-01T03:59:00',
 '2019-01-01T04:00:00',
 '2019-01-01T04:01:00',
 '2019-01-01T04:02:00',
 '2019-01-01T04:03:00',
 '2019-01-01T04:04:00',
 '2019-01-01T04:05:00',
 '2019-01-01T04:06:00',
 '2019-01-01T04:07:00',
 '2019-01-01T04:08:00',
 '2019-01-01T04:09:00',
 '2019-01-01T04:10:00',
 '2019-01-01T04:11:00',
 '2019-01-01T04:12:00',
 '2019-01-01T04:13:00',
 '2019-01-01T04:14:00',
 '2019-01-01T04:15:00',
 '2019-01-01T04:16:00',
 '2019-01-01T04:17:00',
 '2019-01-01T04:18:00',
 '2019-01-01T04:19:00',
 '2019-01-01T04:20:00',
 '2019-01-01T04:21:00',
 '2019-01-01T04:22:00',
 '2019-01-01T04:23:00',
 '2019-01-01T04:24:00',
 '2019-01-01T04:25:00',
 '2019-01-01T04:26:00',
 '2019-01-01T04:27:00',
 '2019-01-01T04:28:00',
 '2019-01-01T04:29:00',
 '2019-01-01T04:30:00',
 '2019-01-01T04:31:00',
 '2019-01-01T04:32:00',
 '2019-01-01T04:33:00',
 '2019-01-01T04:34:00',
 '2019-01-01T04:35:00',
 '2019-01-01T04:36:00',
 '2019-01-01T04:37:00',
 '2019-01-01T04:38:00',
 '2019-01-01T04:39:00',
 '2019-01-01T04:40:00',
 '2019-01-01T04:41:00',
 '2019-01-01T04:42:00',
 '2019-01-01T04:43:00',
 '2019-01-01T04:44:00',
 '2019-01-01T04:45:00',
 '2019-01-01T04:46:00',
 '2019-01-01T04:47:00',
 '2019-01-01T04:48:00',
 '2019-01-01T04:49:00',
 '2019-01-01T04:50:00',
 '2019-01-01T04:51:00',
 '2019-01-01T04:52:00',
 '2019-01-01T04:53:00',
 '2019-01-01T04:54:00',
 '2019-01-01T04:55:00',
 '2019-01-01T04:56:00',
 '2019-01-01T04:57:00',
 '2019-01-01T04:58:00',
 '2019-01-01T04:59:00',
 '2019-01-01T05:00:00',
 '2019-01-01T05:01:00',
 '2019-01-01T05:02:00',
 '2019-01-01T05:03:00',
 '2019-01-01T05:04:00',
 '2019-01-01T05:05:00',
 '2019-01-01T05:06:00',
 '2019-01-01T05:07:00',
 '2019-01-01T05:08:00',
 '2019-01-01T05:09:00',
 '2019-01-01T05:10:00',
 '2019-01-01T05:11:00',
 '2019-01-01T05:12:00',
 '2019-01-01T05:13:00',
 '2019-01-01T05:14:00',
 '2019-01-01T05:15:00',
 '2019-01-01T05:16:00',
 '2019-01-01T05:17:00',
 '2019-01-01T05:18:00',
 '2019-01-01T05:19:00',
 '2019-01-01T05:20:00',
 '2019-01-01T05:21:00',
 '2019-01-01T05:22:00',
 '2019-01-01T05:23:00',
 '2019-01-01T05:24:00',
 '2019-01-01T05:25:00',
 '2019-01-01T05:26:00',
 '2019-01-01T05:27:00',
 '2019-01-01T05:28:00',
 '2019-01-01T05:29:00',
 '2019-01-01T05:30:00',
 '2019-01-01T05:31:00',
 '2019-01-01T05:32:00',
 '2019-01-01T05:33:00',
 '2019-01-01T05:34:00',
 '2019-01-01T05:35:00',
 '2019-01-01T05:36:00',
 '2019-01-01T05:37:00',
 '2019-01-01T05:38:00',
 '2019-01-01T05:39:00',
 '2019-01-01T05:40:00',
 '2019-01-01T05:41:00',
 '2019-01-01T05:42:00',
 '2019-01-01T05:43:00',
 '2019-01-01T05:44:00',
 '2019-01-01T05:45:00',
 '2019-01-01T05:46:00',
 '2019-01-01T05:47:00',
 '2019-01-01T05:48:00',
 '2019-01-01T05:49:00',
 '2019-01-01T05:50:00',
 '2019-01-01T05:51:00',
 '2019-01-01T05:52:00',
 '2019-01-01T05:53:00',
 '2019-01-01T05:54:00',
 '2019-01-01T05:55:00',
 '2019-01-01T05:56:00',
 '2019-01-01T05:57:00',
 '2019-01-01T05:58:00',
 '2019-01-01T05:59:00',
 '2019-01-01T06:00:00',
 '2019-01-01T06:01:00',
 '2019-01-01T06:02:00',
 '2019-01-01T06:03:00',
 '2019-01-01T06:04:00',
 '2019-01-01T06:05:00',
 '2019-01-01T06:06:00',
 '2019-01-01T06:07:00',
 '2019-01-01T06:08:00',
 '2019-01-01T06:09:00',
 '2019-01-01T06:10:00',
 '2019-01-01T06:11:00',
 '2019-01-01T06:12:00',
 '2019-01-01T06:13:00',
 '2019-01-01T06:14:00',
 '2019-01-01T06:15:00',
 '2019-01-01T06:16:00',
 '2019-01-01T06:17:00',
 '2019-01-01T06:18:00',
 '2019-01-01T06:19:00',
 '2019-01-01T06:20:00',
 '2019-01-01T06:21:00',
 '2019-01-01T06:22:00',
 '2019-01-01T06:23:00',
 '2019-01-01T06:24:00',
 '2019-01-01T06:25:00',
 '2019-01-01T06:26:00',
 '2019-01-01T06:27:00',
 '2019-01-01T06:28:00',
 '2019-01-01T06:29:00',
 '2019-01-01T06:30:00',
 '2019-01-01T06:31:00',
 '2019-01-01T06:32:00',
 '2019-01-01T06:33:00',
 '2019-01-01T06:34:00',
 '2019-01-01T06:35:00',
 '2019-01-01T06:36:00',
 '2019-01-01T06:37:00',
 '2019-01-01T06:38:00',
 '2019-01-01T06:39:00',
 '2019-01-01T06:40:00',
 '2019-01-01T06:41:00',
 '2019-01-01T06:42:00',
 '2019-01-01T06:43:00',
 '2019-01-01T06:44:00',
 '2019-01-01T06:45:00',
 '2019-01-01T06:46:00',
 '2019-01-01T06:47:00',
 '2019-01-01T06:48:00',
 '2019-01-01T06:49:00',
 '2019-01-01T06:50:00',
 '2019-01-01T06:51:00',
 '2019-01-01T06:52:00',
 '2019-01-01T06:53:00',
 '2019-01-01T06:54:00',
 '2019-01-01T06:55:00',
 '2019-01-01T06:56:00',
 '2019-01-01T06:57:00',
 '2019-01-01T06:58:00',
 '2019-01-01T06:59:00',
 '2019-01-01T07:00:00',
 '2019-01-01T07:01:00',
 '2019-01-01T07:02:00',
 '2019-01-01T07:03:00',
 '2019-01-01T07:04:00',
 '2019-01-01T07:05:00',
 '2019-01-01T07:06:00',
 '2019-01-01T07:07:00',
 '2019-01-01T07:08:00',
 '2019-01-01T07:09:00',
 '2019-01-01T07:10:00',
 '2019-01-01T07:11:00',
 '2019-01-01T07:12:00',
 '2019-01-01T07:13:00',
 '2019-01-01T07:14:00',
 '2019-01-01T07:15:00',
 '2019-01-01T07:16:00',
 '2019-01-01T07:17:00',
 '2019-01-01T07:18:00',
 '2019-01-01T07:19:00',
 '2019-01-01T07:20:00',
 '2019-01-01T07:21:00',
 '2019-01-01T07:22:00',
 '2019-01-01T07:23:00',
 '2019-01-01T07:24:00',
 '2019-01-01T07:25:00',
 '2019-01-01T07:26:00',
 '2019-01-01T07:27:00',
 '2019-01-01T07:28:00',
 '2019-01-01T07:29:00',
 '2019-01-01T07:30:00',
 '2019-01-01T07:31:00',
 '2019-01-01T07:32:00',
 '2019-01-01T07:33:00',
 '2019-01-01T07:34:00',
 '2019-01-01T07:35:00',
 '2019-01-01T07:36:00',
 '2019-01-01T07:37:00',
 '2019-01-01T07:38:00',
 '2019-01-01T07:39:00',
 '2019-01-01T07:40:00',
 '2019-01-01T07:41:00',
 '2019-01-01T07:42:00',
 '2019-01-01T07:43:00',
 '2019-01-01T07:44:00',
 '2019-01-01T07:45:00',
 '2019-01-01T07:46:00',
 '2019-01-01T07:47:00',
 '2019-01-01T07:48:00',
 '2019-01-01T07:49:00',
 '2019-01-01T07:50:00',
 '2019-01-01T07:51:00',
 '2019-01-01T07:52:00',
 '2019-01-01T07:53:00',
 '2019-01-01T07:54:00',
 '2019-01-01T07:55:00',
 '2019-01-01T07:56:00',
 '2019-01-01T07:57:00',
 '2019-01-01T07:58:00',
 '2019-01-01T07:59:00',
 '2019-01-01T08:00:00',
 '2019-01-01T08:01:00',
 '2019-01-01T08:02:00',
 '2019-01-01T08:03:00',
 '2019-01-01T08:04:00',
 '2019-01-01T08:05:00',
 '2019-01-01T08:06:00',
 '2019-01-01T08:07:00',
 '2019-01-01T08:08:00',
 '2019-01-01T08:09:00',
 '2019-01-01T08:10:00',
 '2019-01-01T08:11:00',
 '2019-01-01T08:12:00',
 '2019-01-01T08:13:00',
 '2019-01-01T08:14:00',
 '2019-01-01T08:15:00',
 '2019-01-01T08:16:00',
 '2019-01-01T08:17:00',
 '2019-01-01T08:18:00',
 '2019-01-01T08:19:00',
 '2019-01-01T08:20:00',
 '2019-01-01T08:21:00',
 '2019-01-01T08:22:00',
 '2019-01-01T08:23:00',
 '2019-01-01T08:24:00',
 '2019-01-01T08:25:00',
 '2019-01-01T08:26:00',
 '2019-01-01T08:27:00',
 '2019-01-01T08:28:00',
 '2019-01-01T08:29:00',
 '2019-01-01T08:30:00',
 '2019-01-01T08:31:00',
 '2019-01-01T08:32:00',
 '2019-01-01T08:33:00',
 '2019-01-01T08:34:00',
 '2019-01-01T08:35:00',
 '2019-01-01T08:36:00',
 '2019-01-01T08:37:00',
 '2019-01-01T08:38:00',
 '2019-01-01T08:39:00',
 '2019-01-01T08:40:00',
 '2019-01-01T08:41:00',
 '2019-01-01T08:42:00',
 '2019-01-01T08:43:00',
 '2019-01-01T08:44:00',
 '2019-01-01T08:45:00',
 '2019-01-01T08:46:00',
 '2019-01-01T08:47:00',
 '2019-01-01T08:48:00',
 '2019-01-01T08:49:00',
 '2019-01-01T08:50:00',
 '2019-01-01T08:51:00',
 '2019-01-01T08:52:00',
 '2019-01-01T08:53:00',
 '2019-01-01T08:54:00',
 '2019-01-01T08:55:00',
 '2019-01-01T08:56:00',
 '2019-01-01T08:57:00',
 '2019-01-01T08:58:00',
 '2019-01-01T08:59:00',
 '2019-01-01T09:00:00',
 '2019-01-01T09:01:00',
 '2019-01-01T09:02:00',
 '2019-01-01T09:03:00',
 '2019-01-01T09:04:00',
 '2019-01-01T09:05:00',
 '2019-01-01T09:06:00',
 '2019-01-01T09:07:00',
 '2019-01-01T09:08:00',
 '2019-01-01T09:09:00',
 '2019-01-01T09:10:00',
 '2019-01-01T09:11:00',
 '2019-01-01T09:12:00',
 '2019-01-01T09:13:00',
 '2019-01-01T09:14:00',
 '2019-01-01T09:15:00',
 '2019-01-01T09:16:00',
 '2019-01-01T09:17:00',
 '2019-01-01T09:18:00',
 '2019-01-01T09:19:00',
 '2019-01-01T09:20:00',
 '2019-01-01T09:21:00',
 '2019-01-01T09:22:00',
 '2019-01-01T09:23:00',
 '2019-01-01T09:24:00',
 '2019-01-01T09:25:00',
 '2019-01-01T09:26:00',
 '2019-01-01T09:27:00',
 '2019-01-01T09:28:00',
 '2019-01-01T09:29:00',
 '2019-01-01T09:30:00',
 '2019-01-01T09:31:00',
 '2019-01-01T09:32:00',
 '2019-01-01T09:33:00',
 '2019-01-01T09:34:00',
 '2019-01-01T09:35:00',
 '2019-01-01T09:36:00',
 '2019-01-01T09:37:00',
 '2019-01-01T09:38:00',
 '2019-01-01T09:39:00',
 '2019-01-01T09:40:00',
 '2019-01-01T09:41:00',
 '2019-01-01T09:42:00',
 '2019-01-01T09:43:00',
 '2019-01-01T09:44:00',
 '2019-01-01T09:45:00',
 '2019-01-01T09:46:00',
 '2019-01-01T09:47:00',
 '2019-01-01T09:48:00',
 '2019-01-01T09:49:00',
 '2019-01-01T09:50:00',
 '2019-01-01T09:51:00',
 '2019-01-01T09:52:00',
 '2019-01-01T09:53:00',
 '2019-01-01T09:54:00',
 '2019-01-01T09:55:00',
 '2019-01-01T09:56:00',
 '2019-01-01T09:57:00',
 '2019-01-01T09:58:00',
 '2019-01-01T09:59:00',
 '2019-01-01T10:00:00',
 '2019-01-01T10:01:00',
 '2019-01-01T10:02:00',
 '2019-01-01T10:03:00',
 '2019-01-01T10:04:00',
 '2019-01-01T10:05:00',
 '2019-01-01T10:06:00',
 '2019-01-01T10:07:00',
 '2019-01-01T10:08:00',
 '2019-01-01T10:09:00',
 '2019-01-01T10:10:00',
 '2019-01-01T10:11:00',
 '2019-01-01T10:12:00',
 '2019-01-01T10:13:00',
 '2019-01-01T10:14:00',
 '2019-01-01T10:15:00',
 '2019-01-01T10:16:00',
 '2019-01-01T10:17:00',
 '2019-01-01T10:18:00',
 '2019-01-01T10:19:00',
 '2019-01-01T10:20:00',
 '2019-01-01T10:21:00',
 '2019-01-01T10:22:00',
 '2019-01-01T10:23:00',
 '2019-01-01T10:24:00',
 '2019-01-01T10:25:00',
 '2019-01-01T10:26:00',
 '2019-01-01T10:27:00',
 '2019-01-01T10:28:00',
 '2019-01-01T10:29:00',
 '2019-01-01T10:30:00',
 '2019-01-01T10:31:00',
 '2019-01-01T10:32:00',
 '2019-01-01T10:33:00',
 '2019-01-01T10:34:00',
 '2019-01-01T10:35:00',
 '2019-01-01T10:36:00',
 '2019-01-01T10:37:00',
 '2019-01-01T10:38:00',
 '2019-01-01T10:39:00',
 '2019-01-01T10:40:00',
 '2019-01-01T10:41:00',
 '2019-01-01T10:42:00',
 '2019-01-01T10:43:00',
 '2019-01-01T10:44:00',
 '2019-01-01T10:45:00',
 '2019-01-01T10:46:00',
 '2019-01-01T10:47:00',
 '2019-01-01T10:48:00',
 '2019-01-01T10:49:00',
 '2019-01-01T10:50:00',
 '2019-01-01T10:51:00',
 '2019-01-01T10:52:00',
 '2019-01-01T10:53:00',
 '2019-01-01T10:54:00',
 '2019-01-01T10:55:00',
 '2019-01-01T10:56:00',
 '2019-01-01T10:57:00',
 '2019-01-01T10:58:00',
 '2019-01-01T10:59:00',
 '2019-01-01T11:00:00',
 '2019-01-01T11:01:00',
 '2019-01-01T11:02:00',
 '2019-01-01T11:03:00',
 '2019-01-01T11:04:00',
 '2019-01-01T11:05:00',
 '2019-01-01T11:06:00',
 '2019-01-01T11:07:00',
 '2019-01-01T11:08:00',
 '2019-01-01T11:09:00',
 '2019-01-01T11:10:00',
 '2019-01-01T11:11:00',
 '2019-01-01T11:12:00',
 '2019-01-01T11:13:00',
 '2019-01-01T11:14:00',
 '2019-01-01T11:15:00',
 '2019-01-01T11:16:00',
 '2019-01-01T11:17:00',
 '2019-01-01T11:18:00',
 '2019-01-01T11:19:00',
 '2019-01-01T11:20:00',
 '2019-01-01T11:21:00',
 '2019-01-01T11:22:00',
 '2019-01-01T11:23:00',
 '2019-01-01T11:24:00',
 '2019-01-01T11:25:00',
 '2019-01-01T11:26:00',
 '2019-01-01T11:27:00',
 '2019-01-01T11:28:00',
 '2019-01-01T11:29:00',
 '2019-01-01T11:30:00',
 '2019-01-01T11:31:00',
 '2019-01-01T11:32:00',
 '2019-01-01T11:33:00',
 '2019-01-01T11:34:00',
 '2019-01-01T11:35:00',
 '2019-01-01T11:36:00',
 '2019-01-01T11:37:00',
 '2019-01-01T11:38:00',
 '2019-01-01T11:39:00',
 '2019-01-01T11:40:00',
 '2019-01-01T11:41:00',
 '2019-01-01T11:42:00',
 '2019-01-01T11:43:00',
 '2019-01-01T11:44:00',
 '2019-01-01T11:45:00',
 '2019-01-01T11:46:00',
 '2019-01-01T11:47:00',
 '2019-01-01T11:48:00',
 '2019-01-01T11:49:00',
 '2019-01-01T11:50:00',
 '2019-01-01T11:51:00',
 '2019-01-01T11:52:00',
 '2019-01-01T11:53:00',
 '2019-01-01T11:54:00',
 '2019-01-01T11:55:00',
 '2019-01-01T11:56:00',
 '2019-01-01T11:57:00',
 '2019-01-01T11:58:00',
 '2019-01-01T11:59:00',
 '2019-01-01T12:00:00',
 '2019-01-01T12:01:00',
 '2019-01-01T12:02:00',
 '2019-01-01T12:03:00',
 '2019-01-01T12:04:00',
 '2019-01-01T12:05:00',
 '2019-01-01T12:06:00',
 '2019-01-01T12:07:00',
 '2019-01-01T12:08:00',
 '2019-01-01T12:09:00',
 '2019-01-01T12:10:00',
 '2019-01-01T12:11:00',
 '2019-01-01T12:12:00',
 '2019-01-01T12:13:00',
 '2019-01-01T12:14:00',
 '2019-01-01T12:15:00',
 '2019-01-01T12:16:00',
 '2019-01-01T12:17:00',
 '2019-01-01T12:18:00',
 '2019-01-01T12:19:00',
 '2019-01-01T12:20:00',
 '2019-01-01T12:21:00',
 '2019-01-01T12:22:00',
 '2019-01-01T12:23:00',
 '2019-01-01T12:24:00',
 '2019-01-01T12:25:00',
 '2019-01-01T12:26:00',
 '2019-01-01T12:27:00',
 '2019-01-01T12:28:00',
 '2019-01-01T12:29:00',
 '2019-01-01T12:30:00',
 '2019-01-01T12:31:00',
 '2019-01-01T12:32:00',
 '2019-01-01T12:33:00',
 '2019-01-01T12:34:00',
 '2019-01-01T12:35:00',
 '2019-01-01T12:36:00',
 '2019-01-01T12:37:00',
 '2019-01-01T12:38:00',
 '2019-01-01T12:39:00',
 '2019-01-01T12:40:00',
 '2019-01-01T12:41:00',
 '2019-01-01T12:42:00',
 '2019-01-01T12:43:00',
 '2019-01-01T12:44:00',
 '2019-01-01T12:45:00',
 '2019-01-01T12:46:00',
 '2019-01-01T12:47:00',
 '2019-01-01T12:48:00',
 '2019-01-01T12:49:00',
 '2019-01-01T12:50:00',
 '2019-01-01T12:51:00',
 '2019-01-01T12:52:00',
 '2019-01-01T12:53:00',
 '2019-01-01T12:54:00',
 '2019-01-01T12:55:00',
 '2019-01-01T12:56:00',
 '2019-01-01T12:57:00',
 '2019-01-01T12:58:00',
 '2019-01-01T12:59:00',
 '2019-01-01T13:00:00',
 '2019-01-01T13:01:00',
 '2019-01-01T13:02:00',
 '2019-01-01T13:03:00',
 '2019-01-01T13:04:00',
 '2019-01-01T13:05:00',
 '2019-01-01T13:06:00',
 '2019-01-01T13:07:00',
 '2019-01-01T13:08:00',
 '2019-01-01T13:09:00',
 '2019-01-01T13:10:00',
 '2019-01-01T13:11:00',
 '2019-01-01T13:12:00',
 '2019-01-01T13:13:00',
 '2019-01-01T13:14:00',
 '2019-01-01T13:15:00',
 '2019-01-01T13:16:00',
 '2019-01-01T13:17:00',
 '2019-01-01T13:18:00',
 '2019-01-01T13:19:00',
 '2019-01-01T13:20:00',
 '2019-01-01T13:21:00',
 '2019-01-01T13:22:00',
 '2019-01-01T13:23:00',
 '2019-01-01T13:24:00',
 '2019-01-01T13:25:00',
 '2019-01-01T13:26:00',
 '2019-01-01T13:27:00',
 '2019-01-01T13:28:00',
 '2019-01-01T13:29:00',
 '2019-01-01T13:30:00',
 '2019-01-01T13:31:00',
 '2019-01-01T13:32:00',
 '2019-01-01T13:33:00',
 '2019-01-01T13:34:00',
 '2019-01-01T13:35:00',
 '2019-01-01T13:36:00',
 '2019-01-01T13:37:00',
 '2019-01-01T13:38:00',
 '2019-01-01T13:39:00',
 '2019-01-01T13:40:00',
 '2019-01-01T13:41:00',
 '2019-01-01T13:42:00',
 '2019-01-01T13:43:00',
 '2019-01-01T13:44:00',
 '2019-01-01T13:45:00',
 '2019-01-01T13:46:00',
 '2019-01-01T13:47:00',
 '2019-01-01T13:48:00',
 '2019-01-01T13:49:00',
 '2019-01-01T13:50:00',
 '2019-01-01T13:51:00',
 '2019-01-01T13:52:00',

### Step 4: Calling API for the list of datetimes

In [ ]:
# Step 4: Call API and get a list of JSON objects
# Step 3a: Declare the request URL
import json
list_jsons=[]
url="https://api.data.gov.sg/v1/transport/traffic-images"
# Step 3b: Make an API request and save the results in a variable
for i in date_range_string:
  params={
    "date_time" : str(i),
  }
  data=requests.get(url,params=params)

  # Step 5b: declare another variable, and save the JSON in it
  data_json=data.json()
  # Step 5c: peek at your JSON
  list_jsons.append(data_json)

### Step 5: Combine all the JSON into a DataFrame

In [ ]:
# Step 5: Combine the list of JSON into a DataFrame
data=pd.json_normalize(list_jsons,record_path =['items','cameras'])
data.head()

,timestamp,image,camera_id,location.latitude,location.longitude,image_metadata.height,image_metadata.width,image_metadata.md5
0,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1501,1.274144,103.851317,240,320,95feb086c24db3ac1be9b1e6dc194194
1,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1502,1.271351,103.861828,240,320,d2dbeaed33ac9a523eb8f9a4138657d0
2,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1503,1.270664,103.856978,240,320,fdd3313e5a4a2b786444a7371db349c9
3,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1504,1.294099,103.876056,240,320,b8f1220bff0f26bc0ec11521e2b16fc1
4,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1505,1.275298,103.866390,240,320,ba53008cf3198ed272e8d35e52db1354

In [ ]:
data.shape

(124874, 8)

In [ ]:
data.to_csv("data.csv")
from google.colab import files
files.download('/content/data.csv')

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/traffic/data.csv",index_col=[0])
data.head()

,timestamp,image,camera_id,location.latitude,location.longitude,image_metadata.height,image_metadata.width,image_metadata.md5
0,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1501,1.274144,103.851317,240,320,95feb086c24db3ac1be9b1e6dc194194
1,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1502,1.271351,103.861828,240,320,d2dbeaed33ac9a523eb8f9a4138657d0
2,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1503,1.270664,103.856978,240,320,fdd3313e5a4a2b786444a7371db349c9
3,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1504,1.294099,103.876056,240,320,b8f1220bff0f26bc0ec11521e2b16fc1
4,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1505,1.275298,103.866390,240,320,ba53008cf3198ed272e8d35e52db1354

### Step 6: Filter the DataFrame for camera 1709 only
Your huge DataFrame currently contains the URLs for the images from ALL cameras in a single day.

Filter the DataFrame to contain only rows from <strong>camera_id = 1709</strong> so we can see how many rows there are in a single day.

In [ ]:
# Step 6: Filter for 1709
data_1709=data[data["camera_id"]==1709]
data_1709.head()

,timestamp,image,camera_id,location.latitude,location.longitude,image_metadata.height,image_metadata.width,image_metadata.md5
11,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,48f34eaa179e51989c8f937631da1bce
91,2019-01-01T00:00:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,ed9a57e100a83156605b19ec84bdc2fe
182,2019-01-01T00:01:25+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,c2713943d69482eaa4191454c76af1c8
269,2019-01-01T00:01:25+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,c2713943d69482eaa4191454c76af1c8
359,2019-01-01T00:03:45+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,7892491f53adea153a2345de7d5e6873

### Step 7: Drop duplicates based on 'image'
If you observe carefully, there are some rows that are repeated.

In [ ]:
# Step 7: Drop duplicates by 'image' column
data_1709.drop_duplicates(subset="image",inplace=True)
data_1709

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,timestamp,image,camera_id,location.latitude,location.longitude,image_metadata.height,image_metadata.width,image_metadata.md5
11,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,48f34eaa179e51989c8f937631da1bce
91,2019-01-01T00:00:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,ed9a57e100a83156605b19ec84bdc2fe
182,2019-01-01T00:01:25+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,c2713943d69482eaa4191454c76af1c8
359,2019-01-01T00:03:45+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,7892491f53adea153a2345de7d5e6873
534,2019-01-01T00:05:25+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,fa2696a66b3c5bb982e26b765f2d1b98
...,...,...,...,...,...,...,...,...
124106,2019-01-01T23:51:30+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,fb005565f6799a77241ba188f296ca67
124278,2019-01-01T23:53:10+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,254b0fff67ec209fcf926c74cfe86d06
124369,2019-01-01T23:54:30+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,fc7442dfe716cae26f667bacec37e143
124455,2019-01-01T23:55:30+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,df9921dd797b6f470ccc4271c609667c
124622,2019-01-01T23:57:30+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,3ce2dc2e7827af15b35c260ec5dc0753

# Full data collection

### Step 8: Set up date_ranges

In [ ]:
# Step 8a: Set up date range for 2019
date_range_2019=pd.date_range(start='1/1/2019', end='1/2/2019',freq="1T")
date_range_2019

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 00:01:00',
               '2019-01-01 00:02:00', '2019-01-01 00:03:00',
               '2019-01-01 00:04:00', '2019-01-01 00:05:00',
               '2019-01-01 00:06:00', '2019-01-01 00:07:00',
               '2019-01-01 00:08:00', '2019-01-01 00:09:00',
               ...
               '2019-01-01 23:51:00', '2019-01-01 23:52:00',
               '2019-01-01 23:53:00', '2019-01-01 23:54:00',
               '2019-01-01 23:55:00', '2019-01-01 23:56:00',
               '2019-01-01 23:57:00', '2019-01-01 23:58:00',
               '2019-01-01 23:59:00', '2019-01-02 00:00:00'],
              dtype='datetime64[ns]', length=1441, freq='T')

In [ ]:
# Step 8b: Set up date range for 2020
date_range_2020=pd.date_range(start='1/1/2020', end='1/2/2020',freq="1T")
date_range_2020

DatetimeIndex(['2020-01-01 00:00:00', '2020-01-01 00:01:00',
               '2020-01-01 00:02:00', '2020-01-01 00:03:00',
               '2020-01-01 00:04:00', '2020-01-01 00:05:00',
               '2020-01-01 00:06:00', '2020-01-01 00:07:00',
               '2020-01-01 00:08:00', '2020-01-01 00:09:00',
               ...
               '2020-01-01 23:51:00', '2020-01-01 23:52:00',
               '2020-01-01 23:53:00', '2020-01-01 23:54:00',
               '2020-01-01 23:55:00', '2020-01-01 23:56:00',
               '2020-01-01 23:57:00', '2020-01-01 23:58:00',
               '2020-01-01 23:59:00', '2020-01-02 00:00:00'],
              dtype='datetime64[ns]', length=1441, freq='T')

### Step 9: Define retrieveCameraJSON
Defining a function called retrieveCameraJSON where it takes in one argument - url.

<details>
<summary>Click here for pseudocode if you need help</summary>
  <ol>
    <li><strong>Define</strong> retrieveCameraJSON, taking in one argument called date_time</li>
    <li>In the function definition</li>
    <ul>
    <li>Declare a variable that contains the base URL, just before date_time=</li>
    <li>Declare a variable that takes the base URL and combines it with the formatted date_time argument (refer to Step 3)</li>
    <li>Make a GET request to get the response of the API call</li>
    <li>Declare a varible to store the JSON data of the response</li>
    <li><strong>Return</strong> the variable</li>
    </ul>
  </ol>
</details>

In [ ]:
# Step 9: Define retrieveCameraJSON
def retrieveCameraJSON(date_time):
  url="https://api.data.gov.sg/v1/transport/traffic-images"
  date_range_string=str(date_time)[:10]+"T"+str(date_time)[11:]
  import json
  params={
    "date_time" : str(date_range_string),
  }
  data=requests.get(url,params=params)

  data_json=data.json()

  return data_json

### Step 10: Import library
Since we're doing concurrency, we'll need:
- futures from concurrent

In [ ]:
# Step 10: Import futures
from concurrent import futures

### Step 11: Use concurrency to retrieve JSON data from 2019

In [ ]:
# Step 11a: Make concurrent API calls for 2019 data
result=[]
with futures.ThreadPoolExecutor(max_workers=150) as executor:
    future_to_url = {executor.submit(retrieveCameraJSON,dt) for dt in date_range_2019}
    for future in futures.as_completed(future_to_url):
        result.append(future.result())

In [ ]:
# Step 11b: Get length of list of JSON results
len(result)

1441

### Step 12:get 2019 Jan DataFrame

In [ ]:
# Step 12: Get the 2019 Jan DataFrame
date_range=pd.date_range(start='1/1/2019', end='2/1/2019',freq="1T")
print(len(date_range))
result=[]
with futures.ThreadPoolExecutor(max_workers=500) as executor:
    future_to_url = {executor.submit(retrieveCameraJSON,dt) for dt in date_range}
    for future in futures.as_completed(future_to_url):
        result.append(future.result())
        print(len(result))

In [ ]:
data_jan=pd.json_normalize(result,record_path =['items','cameras'])
data_jan.head()

,timestamp,image,camera_id,location.latitude,location.longitude,image_metadata.height,image_metadata.width,image_metadata.md5
0,2019-01-02T06:48:30+08:00,https://images.data.gov.sg/api/traffic-images/...,1001,1.295313,103.871146,240,320,49d7d69a71d1c2e69af26df78cffd77c
1,2019-01-02T06:48:30+08:00,https://images.data.gov.sg/api/traffic-images/...,1002,1.319541,103.878563,240,320,0130c3f8b96322607097626447a7bc68
2,2019-01-02T06:48:30+08:00,https://images.data.gov.sg/api/traffic-images/...,1003,1.323957,103.872858,240,320,51be046da41b7c5aa402cdd94cac21a8
3,2019-01-02T06:48:30+08:00,https://images.data.gov.sg/api/traffic-images/...,1004,1.319536,103.875067,240,320,b86dd8af8b7720b6a0d4c8381ca51a6a
4,2019-01-02T06:48:30+08:00,https://images.data.gov.sg/api/traffic-images/...,1005,1.363520,103.905394,240,320,3e0337bdf43804e8dd6358e806831568

In [ ]:
data_jan.drop_duplicates(subset="image",inplace=True)
print("Shape : ", data_jan.shape)

Shape :  (1392293, 8)

In [ ]:
data_1709=data_jan[data_jan["camera_id"]=='1709']
data_1709.drop_duplicates(subset="image",inplace=True)
print("Shape : ", data_1709.shape)
data_1709.head()

Shape :  (30236, 8)

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,timestamp,image,camera_id,location.latitude,location.longitude,image_metadata.height,image_metadata.width,image_metadata.md5
18,2019-01-02T06:48:30+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,bf04989e401ad21f462d65c7ec548e2d
92,2019-01-01T20:30:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,3064471d2c9a9f75305f1c67fc5f5216
183,2019-01-01T03:58:35+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,80a14c997010031aee018342f6a6cc15
263,2019-01-02T03:09:19+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,7a8046d7d0a432b1c2a14f531db0b8cf
352,2019-01-02T06:45:50+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,8685af59168d84464ceaacb38df66553

### Step 13: Sort the DataFrame by timestamp
Using concurrency meant that the JSON in the list is not ordered chronologically.

In [ ]:
# Step 13: Sort the DataFrame by timestamp
data_1709.sort_values(by=["timestamp"])

,timestamp,image,camera_id,location.latitude,location.longitude,image_metadata.height,image_metadata.width,image_metadata.md5
48293,2018-12-31T23:59:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,48f34eaa179e51989c8f937631da1bce
21172,2019-01-01T00:00:44+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,ed9a57e100a83156605b19ec84bdc2fe
17374,2019-01-01T00:01:25+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,c2713943d69482eaa4191454c76af1c8
60714,2019-01-01T00:03:45+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,7892491f53adea153a2345de7d5e6873
5861,2019-01-01T00:05:25+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,fa2696a66b3c5bb982e26b765f2d1b98
...,...,...,...,...,...,...,...,...
3827993,2019-01-31T23:54:47+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,d070313c2ca6bde6c44a074d136dcf05
3830159,2019-01-31T23:56:27+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,41786bfddd62f3138dd9d71b6210af28
3830066,2019-01-31T23:57:27+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,afd6213f51bda947cc27b98082c21f53
3829203,2019-01-31T23:58:27+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,0c172e9da57d5e8e241d6ca05e25347e
3831205,2019-01-31T23:59:47+08:00,https://images.data.gov.sg/api/traffic-images/...,1709,1.313842,103.845603,480,640,20b727575a2fd8218aaf857370137bfb

### Step 14: Export the DataFrame into a CSV file

In [ ]:
# Step 14: Export the DataFrame into CSV
data_1709.to_csv("/content/drive/MyDrive/traffic/formated_data_1709.csv")

In [ ]:
data_jan.to_csv("/content/drive/MyDrive/traffic/formated_data_jan.csv")

### Step 15: Repeat Steps 11-14 for date range in 2020
Now that you're done with 2019, time to collect data for 2020 Jan.

In [ ]:
# Step 15: Repeat Steps 11-14 for 2020 data
date_range=pd.date_range(start='1/1/2020', end='2/1/2020',freq="1T")
print(len(date_range))
result=[]
with futures.ThreadPoolExecutor(max_workers=1000) as executor:
    future_to_url = {executor.submit(retrieveCameraJSON,dt) for dt in date_range}
    for future in futures.as_completed(future_to_url):
        result.append(future.result())
        print(len(result))


data_jan=pd.json_normalize(result,record_path =['items','cameras'])
print("Shape before : ", data_jan.shape)

data_jan.drop_duplicates(subset="image",inplace=True)
print("Shape after : ", data_jan.shape)

data_1709=data_jan[data_jan["camera_id"]=='1709']
data_1709.drop_duplicates(subset="image",inplace=True)
print("Shape of camera_id=1709 data: ", data_1709.shape)

data_1709.to_csv("/content/drive/MyDrive/traffic/formated_data_1709_2020.csv")
data_jan.to_csv("/content/drive/MyDrive/traffic/formated_data_jan_2020.csv")